INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project 1', 'websites', '25000', '2021-01-01', '2021-02-01');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project 2', 'websites', '35000', '2021-02-01', '2021-03-01');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project 3', 'websites', '45000', '2021-03-01', '2021-04-01');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project 4', 'websites', '55000', '2021-04-01', '2021-05-01');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project 5', 'websites', '65000', '2021-05-01', '2021-06-01');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project 6', 'apps', '75000', '2021-06-01', '2021-07-01');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project 7', 'apps', '85000', '2021-07-01', '2021-08-01');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project 8', 'apps', '95000', '2021-08-01', '2021-09-01');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project 9', 'apps', '105000', '2021-09-01', '2021-10-01');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project 10', 'apps', '115000', '2021-10-01', '2021-11-01');

INSERT INTO users (name, age) VALUES ('Bob', 20);
INSERT INTO users (name, age) VALUES ('Dave', 21);
INSERT INTO users (name, age) VALUES ('Warren', 22);
INSERT INTO users (name, age) VALUES ('James', 23);
INSERT INTO users (name, age) VALUES ('Mitchel', 24);
INSERT INTO users (name, age) VALUES ('Alma', 25);
INSERT INTO users (name, age) VALUES ('Richard', 26);
INSERT INTO users (name, age) VALUES ('Curtis', 27);
INSERT INTO users (name, age) VALUES ('Matthew', 28);
INSERT INTO users (name, age) VALUES ('Mary', 29);
INSERT INTO users (name, age) VALUES ('Elizabeth', 30);
INSERT INTO users (name, age) VALUES ('Sandy', 31);
INSERT INTO users (name, age) VALUES ('Margret', 32);
INSERT INTO users (name, age) VALUES ('Martha', 33);
INSERT INTO users (name, age) VALUES ('Jared', 34);
INSERT INTO users (name, age) VALUES ('Chris', 35);
INSERT INTO users (name, age) VALUES ('Luke', 36);
INSERT INTO users (name, age) VALUES ('Lin', 37);
INSERT INTO users (name, age) VALUES ('Dianne', 38);
INSERT INTO users (name, age) VALUES ('Ammon', 39);

INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 2, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (400, 4, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 5, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (600, 6, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (700, 7, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (800, 8, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (900, 9, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 10, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 11, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (400, 13, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 14, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (600, 15, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (700, 16, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (800, 17, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (900, 18, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 19, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 20, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 19, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (400, 18, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 17, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (600, 16, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (700, 15, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (800, 14, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (900, 13, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 12, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 11, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 10, 3);